#
###################################
# Site wide configuration
####################################
#
title: bfansheng
email: bfansheng@gmail.com
description: bfansheng's blog,powered by jekyll.
url: https://bfansheng.github.io # the base hostname & protocol for your site
keywords: ["Programming", "Java", "Blog"]

#
###################################
# Jekyll configuration
####################################
#
timezone:          Asia/Shanghai
markdown:          kramdown
markdown:          redcarpet
highlighter:       rouge
excerpt_separator: '------'
permalink:         /articles/:year-:month/:title

    
kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  enable_coderay: false

#
###################################
# Site Owner configuration
####################################
#
owner:
  name: bfansheng
  avatar: avatar.jpg
  job: "Java Developer"
  bio: "鲜衣怒马少年时，一日看尽长安花"
  email: bfansheng@gmail.com
